# Generated by Django 3.2 on 2021-04-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_survey_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='org',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization'),
        ),
    ]
