# Generated by Django 3.2 on 2021-04-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210420_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='osat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='permission_to_contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='rsn_for_score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='survey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(default=1, max_length=200, null=True),
        ),
    ]
