# Generated by Django 3.2 on 2021-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210425_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='comment',
        ),
        migrations.AlterField(
            model_name='record',
            name='permission_to_contact',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rsn_for_score',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
